
  /login:
    get:
     summary: Get all logins
     tags: [login]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/login'
 
    post:
      summary: Create login
      tags: [login]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login'
 
  /login/{id}:
    get:
      summary: Get login by id
      tags: [login]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login'
 
    put:
      summary: Edit login
      tags: [login]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/login'
 
    delete:
      summary: Delete login
      tags: [login]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /signup:
    get:
     summary: Get all signups
     tags: [signup]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/signup'
 
    post:
      summary: Create signup
      tags: [signup]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signup'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signup'
 
  /signup/{id}:
    get:
      summary: Get signup by id
      tags: [signup]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signup'
 
    put:
      summary: Edit signup
      tags: [signup]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signup'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/signup'
 
    delete:
      summary: Delete signup
      tags: [signup]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signup'

  components:
    schemas:
  
      login:
        type: object
        properties:
      
          id:
            type: string
          email:
            type: string
          password:
            type: string
          user:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: string
          signup:
            type: string
      signup:
        type: object
        properties:
      
          id:
            type: number
          firstname:
            type: string
          lastname:
            type: string
          phonenumber:
            type: number
          gender:
            type: boolean
          password:
            type: string
          confirmpassword:
            type: string